---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

The following code has function and data dependancies from the main arran_workbook.
```{r}
library(sf)
library(ggplot2) #development version!
## devtools::install_github("tidyverse/ggplot2")
library(tidyverse)
library(readr)
## Not sure about this bit
#library("tidyverse",lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
library(cowplot)
library(sp)
library(gridExtra)
library(dplyr)
```

```{r}
plot1 <- simple.sf %>% ggplot() + geom_sf(shape=20) +
theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
plot2 <- arransubsect %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  geom_sf(data=simple.sf, shape=20)
```

```{r}
plot3 <- arran2016 %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  theme(legend.position="none") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  geom_sf(data=simple.sf, shape=20)
```

```{r}
plot4 <-   arransubsect %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  theme(legend.position="none") +
  geom_sf(data= S01004372, aes()) +
  geom_sf(data=function6(2), shape=20)
  
```

```{r}
plot5 <- S01004372 %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  geom_sf(data=function6(2), shape=20) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
grid.arrange(plot1, plot2, plot3, plot4, plot5, nrow = 1)
```

```{r}
plot6 <- arran2016 %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  theme(legend.position="none") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
plot7 <- arran2016 %>%
  ggplot() +
  geom_sf(aes(fill = DataZone)) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
plot8 <- arran2016 %>%
  ggplot() +
  geom_sf(aes(fill = Percentile)) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
grid.arrange(plot6, plot7, plot8, nrow = 1)
```

```{r}
arransimd %>%
  ggplot() +
  geom_sf(aes(fill = Percentile)) +
  facet_wrap('year', nrow = 1) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
function7.5.1(S01004372,2)
```
