---
title: "R Notebook"
output: html_notebook
---

#Interesting but only works for DZ big enough to be seen on map.
```{r}
function4.5 <- function(argument, argument2) 
{
  a <- function1(argument)
  b <- function2(argument) +
  geom_sf(data=function6(argument2))

  plot_grid(a, b, labels = c("A", "B"))
}
```

```{r}
function7 <- function(argument, argument2) 
{
  a <- function1(argument)
  b <- function2(argument)
  c <- function5(argument,argument2)
  plot_grid(a, b, c)
}
```

```{r}
function1.5 <- function(argument) 
{
  argument %>%
  ggplot() +
  geom_sf(aes(fill = Percentile)) +
  facet_wrap('year') +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  theme(legend.position="bottom")  
}
```

```{r}
function2.5 <- function(argument) 
{
  arransubsect %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  theme(axis.text.x=element_text(angle=45, hjust = 1)) +
  theme(legend.position="none") +
  geom_sf(data= argument, aes(fill = DataZone))
}
```

```{r}
function7.5 <- function(argument, argument2) 
{
  a <- function1.5(argument)
  b <- function2.5(argument) 
  c <- function5(argument, argument2)
  grid.arrange(a, b, c, nrow = 1)
}
```


