---
title: "R Notebook"
output: html_notebook
---

#Function 7 Facetted

function7.5.1.2 pre
function7.5.1.2 <- function(argument)
{
  function7.5.1(pre2016list[[argument]],pre2016listID[[argument]])
}

pre2016listID <- list(3,2,1,4,7,6,5)


post2016listID <- list(1,2,3,4,5,6,7)
post2016listID2 <- list(1:7)



function7.5.1.1 post

function7.5.1.1.1 <- function(argument)
{
  function7.5.1(post2016list[[argument]],post2016listID2[[argument]])
}
lapply(1:7, function7.5.1.1.1)


/////


```{r}
simple.sf <- st_as_sf(arrancoordinates, coords=c('longitude','latitude'))
st_crs(simple.sf) <- 4326

exampleshapes <- sf:::as_Spatial(arran20162$geometry)
examplepoints <- sf:::as_Spatial(simple.sf$geom)

examplepoints <- spTransform(examplepoints, CRS("+proj=longlat +datum=WGS84"))
exampleshapes <- spTransform(exampleshapes, CRS("+proj=longlat +datum=WGS84"))

namingdzpostcode <- over(exampleshapes, examplepoints, returnList = TRUE)
```

```{r}
#pre2016listID <- list(3,2,1,4,7,6,5)
#post2016listID <- list(1,2,3,4,5,6,7)

#pre2016listID2 <- list(1,2,3,4,5,6,7)
#post2016listID2 <- list(1,2,3,4,5,6,7)

listID <- list(1,2,3,4,5,6,7)

#all datazones
#datazonelist <- lapply(datazones, function0.5)

#Pre-2016 lists
pre2016list2 <- list("S01004409", "S01004372", "S01004353", "S01004352", "S01004351", "S01004350", "S01004349")
pre2016list <- lapply(pre2016list2, function0.5)

#post2016list2 <- list("S01011177", "S01011171", "S01011174", "S01011176", "S01011172", "S01011173", "S01011175")
#post2016list <- lapply(post2016list2, function0.5)

post2016list3 <- list("S01011174", "S01011171", "S01011177", "S01011176", "S01011175", "S01011173", "S01011172" )
post2016list2 <- lapply(post2016list3, function0.5)
```

```{r}

#rearrange arrancoord
function6 <- function(argument) 
{
  arrancoordinates[namingdzpostcode[[argument]],]
}
```

```{r}
function5 <- function(argument, argument2) 
{
  argument %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  geom_point(data=function6(argument2), mapping = aes(x = longitude, y = latitude), size=1) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
}
```

```{r}
function7.5.1 <- function(argument, argument2) 
{
  a <- function1.5.5(argument)
  b <- function2.5.1(argument) 
  c <- function5(argument, argument2)
  grid.arrange(a, b, c, nrow = 1)
}
```

```{r}
function8.pre <- function(argument)
{
  function7.5.1(pre2016list[[argument]],listID[[argument]])
}
lapply(1:7, function8.pre)

function8.post <- function(argument)
{
  function7.5.1(post2016list2[[argument]],listID[[argument]])
}
lapply(1:7, function8.post)
```

