---
title: "R Notebook"
output: html_notebook
---

```{r}
# !formatR
library(leaflet)
library(rgdal)
library(leaflet)

m = leaflet() %>% addTiles()
```

```{r}
m %>% setView(-5.227680, 55.582338, zoom = 10) %>% 
addMarkers(
    lng = arrancoordinates$longitude, lat = arrancoordinates$latitude,
    label = arrancoordinates$postcode,
    labelOptions = labelOptions(noHide = F)) %>%
  addPolygons(data=exampleshapes, weight = 2)
```

```{r}
leaflet(s2) %>%
  setView(-5.227680, 55.582338, zoom = 10) %>% 
  addPolygons(weight = 1, color = "black", opacity = 1.0, fillOpacity = 0.5) %>% 
  addTiles()

```


```{r}
ggplot() +
  geom_sf(data = arran2016)
```

```{r}
list.files('x:/alldata/SG_SIMD_2016', pattern='\\.shp$')

file.exists('~/dropbox/Arran/alldata/SG_SIMD_2016/SG_SIMD_2016.shp')

readOGR(dsn="~/dropbox/Arran/alldata/SG_SIMD_2016/SG_SIMD_2016", layer="SG_SIMD_2016")

s <- shapefile('~/dropbox/Arran/alldata/SG_SIMD_2016/SG_SIMD_2016.shp')

s2 <- s[Arrandz,]

readOGR(dsn = "x:/alldata/SG_SIMD_2016", layer = "SG_SIMD_2016")
```

```{r}
states <- readOGR("/shp/cb_2013_us_state_20m.shp", layer = "cb_2013_us_state_20m")
```
