---
title: "Making your own maps"
output: html_notebook
---

This is a default template to try and enable you to create your own maps using R.
This assumes you will would like to create a limited number of different plots that I can design step-by-steps for.
Anything more complex would require me to either customise the code which is (probably) simple, or for you to learn a little of R yourself.

Now I've customised this in mind of using common data to represent visually on a map.
With this in mind I've created a reference coordinate look-up, so any data assigned to an Arran postcode can be represented on a map.
For example as a series of points to see the geographical spread.
Or  as a colour coourdinated fill on postcode zones, to show a variable 
change over an area.

Or a combination. The point of this isn't to automate everything, as I can't yet. But with some thought I could customise a code to show, for example a colour-coding to postcode zones which were over an hours drive from the nearest GPs. (Or to the nearest ferrypool).
The point of this is to show a range of possible uses that would be interesting and useful to anyone.

Plot Example 1
#Show a series of points on a map.

read .csv/excel
find column 'postcode'
find column 'variable'

select/mutate coordinates to match postcodes.

plot points. - interactive map.

plot image
overlay roads/foreshore/etc (choose)
scale (choose)

choose scale, export image (save)



