---
title: "R Notebook"
output: html_notebook
---

mapping scraps

```{r}
pal <- colorNumeric(
  palette = "Blues",
  domain = exampleshapes2$Percentile)

leaflet() %>% 
  addTiles() %>% 
  setView(-5.227680, 55.582338, zoom = 10) %>% 

#alldatazones  
addPolygons(data=exampleshapes, 
            weight = 2, 
            label = datazonelist,
            group = "2004",
            highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
hideGroup("2004") %>% 
  
addPolygons(data=exampleshapes, 
            weight = 2, 
            label = datazonelist,
            group = "2006",
            highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
hideGroup("2006") %>% 
  
addPolygons(data=exampleshapes, 
            weight = 2, 
            label = datazonelist,
            group = "2009",
            highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
hideGroup("2009") %>% 
  
addPolygons(data=exampleshapes, 
            weight = 2, 
            label = datazonelist,
            group = "2012",
            highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
hideGroup("2012") %>% 

addPolygons(data=exampleshapes2, 
            weight = 2, 
            label = datazonelist,
            group = "2016",
            highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE)) %>% 
hideGroup("2016") %>% 
  
#cliniccoordinates
addMarkers(
    lng = cliniccoordinates$longitude, lat = cliniccoordinates$latitude,
    label = cliniccoordinates$X,
    labelOptions = labelOptions(noHide = F), group = cliniccoordinates$X) %>%
  hideGroup(cliniccoordinates$X) %>%   
  
#Layers control
addLayersControl(
    baseGroups = c("2004", "2006", "2009", "2012", "2016", "Nothing"),
    overlayGroups = c(cliniccoordinates$X),
    options = layersControlOptions(collapsed = TRUE)
  )
```

```{r}
exampleshapes3 <- as(arransimd, "Spatial") %>%
spTransform(CRS("+proj=longlat +datum=WGS84"))

pal2 <- colorNumeric(
  palette = "Blues",
  domain = exampleshapes3$Percentile)

#exampleshapes3$year=2016

#exampleshapes3[exampleshapes3$year == 2016, ]
  
leaflet() %>% 
  addTiles() %>% 
  setView(-5.227680, 55.582338, zoom = 10) %>% 
addPolygons(data = exampleshapes3[exampleshapes3$year == 2016, ], 
            weight = 2, 
            label = datazonelist,
            group = "2016",
            fillOpacity =0.8,
            color = ~pal2(exampleshapes3$Percentile),
            highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE))

```

```{r}
exampleshapes2 <- as(arran2016, "Spatial") %>%
spTransform(CRS("+proj=longlat +datum=WGS84"))

pal <- colorNumeric(
  palette = "Blues",
  domain = exampleshapes2$Percentile)

leaflet() %>% 
  addTiles() %>% 
  setView(-5.227680, 55.582338, zoom = 10) %>% 
addPolygons(data = exampleshapes2, 
            weight = 2, 
            label = datazonelist,
            group = "2016",
            fillOpacity =0.8,
            color = ~pal(exampleshapes2$Percentile),
            highlightOptions = highlightOptions(color = "black", weight = 2,
      bringToFront = TRUE))

```