---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ggrepel)
```

```{r}
arran2016 %>%
mutate(
    lon = map_dbl(geometry, ~st_centroid(.x)[[1]]),
    lat = map_dbl(geometry, ~st_centroid(.x)[[2]])
    ) %>%

ggplot() +
  geom_sf(aes(fill = DataZone)) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position="none") +
  geom_text(aes(label = DataZone, x = lon, y = lat), size = 2)
```

```{r}
  ggplot() +
  geom_sf(data = arransubsect) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  geom_sf(data= function0.5("S01004372")) +
  geom_point(data=function6(2), mapping = aes(x = longitude, y = latitude), size=1) +
  geom_text(data=function6(2), aes(label = function6(2)$postcode, x = longitude, y = latitude), size = 2) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))

#geom_sf(data=function6(2), colour = function6(2)$postcode, shape=20)
#Different colour don't appear to work in geom_point
```
```{r}
ggplot() +
  geom_sf(data = arransubsect) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  geom_sf(data= function0.5("S01004372")) +
  geom_point(data=function6(2), mapping = aes(x = longitude, y = latitude), size=1) +
  geom_text_repel(data= zone2, aes(label = postcode, x = lon, y = lat), colour = 'blue', size = 2) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
```

```{r}
ggplot() +
  geom_sf(data = arransubsect) +
  geom_text(data = function6(2), 
            aes(label = function6(2)$postcode, 
                x = longitude, y = latitude), size = 2) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
```

```{r}
ggplot() +
  geom_sf(data = arransubsect) +
  geom_label_repel(data = function6(2), 
            aes(label = function6(2)$postcode, 
                x = longitude, y = latitude), size=2) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
```


```{r}
ggplot() +
  geom_text(data= zone2, aes(label = postcode, x = lon, y = lat), size = 2) +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
```
