---
title: "R Notebook"
output: html_notebook
---

```{r}
#label <- arransimd %>%
#  summarise(
#   displ = max(year),
#    hwy = max(Percentile),
#    label = "New DataZones from 2016"
#  )
```


```{r}
namemygrid <- data.frame(
  row = c(1, 1, 2, 2, 3, 3, 4),
  col = c(2, 1, 2, 3, 1, 2, 3),
  code = c("2", "1", "3", "4", "7", "5", "6"),
  name = c("S01004409", "S01004372", "S01004353", "S01004352", "S01004349", "S01004351", "S01004350"),
  stringsAsFactors = FALSE
)
```

```{r}
library(geofacet)
grid_preview(namemygrid)
```


```{r}
mutate(arransimd2)
```


```{r}
ggplot(data=arransimd2, aes(x=year, y=Percentile)) +
  geom_bar(stat="identity") +
  facet_geo(~ 'name', "namemygrid")

, label = 'name')
```


Now I plot these coordinates.
```{r}
## Plotting the Arran coordinates
ggplot(data = arrancoordinates) +
  geom_point(mapping = aes(x = longitude, y = latitude)) +
  ggtitle("Arran Postcodes") +
  labs(title = "Arran Postcodes", x = "Longitude", y = "Latitude") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
pcs <- read_sf("alldata/Scotland_pcs_2011")

#Print Post codes lists
arransubsect <- filter(pcs,substr(label,1,4)=="KA27")
arransubsect %>%
  ggplot() +
  geom_sf() +
  theme(axis.text.x=element_text(angle=45, hjust = 1)) +
  geom_sf(data= S01011177example, aes(fill = DataZone))
```

```{r}
arran20162 %>%
  ggplot() +
  geom_sf(aes(fill = DataZone)) +
  facet_wrap('year') +
  theme(legend.position="none") +
  theme(axis.text.x=element_text(angle=45, hjust = 1))

S01011177example <-dplyr::filter(arran20162, DataZone == "S01011177")



S01011177example %>%
  ggplot() +
  geom_sf(data= S01011177example, aes(fill = DataZone))
```