---
title: "R Notebook"
output: html_notebook
---
I can then use the above, and plot over the appropriate DZ shapefile.
e.g
#Projecting the coordinate selections
#Examples
```{r}
function1(function0.5("S01004372")) +
  geom_point(data=function6(2), mapping = aes(x = longitude, y = latitude), size=1) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
function2(function0.5("S01004372")) +
  geom_point(data=function6(2), mapping = aes(x = longitude, y = latitude), size=1) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
function3(function0.5("S01004372")) +
  geom_point(data=function6(2), mapping = aes(x = longitude, y = latitude), size=1) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
```


```{r}
function1 <- function(argument) 
{
  argument %>%
  ggplot() +
  geom_sf(aes(fill = Percentile)) +
  facet_wrap('year') +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
}
```

```{r}
function2 <- function(argument) 
{
  arransubsect %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  theme(axis.text.x=element_text(angle=45, hjust = 1)) +
  geom_sf(data= argument, aes(fill = DataZone))
}
```

```{r}
function2(S01011177)
```


```{r}
function3 <- function(argument) 
{
  argument %>%
  ggplot() +
  geom_sf(data = arransubsect) +
  geom_sf(aes(fill = Percentile)) +
  facet_wrap('year') +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
}
```

```{r}
function4 <- function(argument) 
{
  plot_grid((function1(argument)), (function2(argument)), labels = c("A", "B"))
}
```

If I edit function 4 a little so that the geom_sf layer is a second argument then I can also use function 4.
```{r}
function4.5 <- function(argument, argument2) 
{
  a <- function1(argument)
  b <- function2(argument) +
  geom_point(data=function6(2), mapping = aes(x = longitude, y = latitude), size=1) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))

  plot_grid(a, b, labels = c("A", "B"))
}
```

```{r}
function7.5 <- function(argument, argument2) 
{
  a <- function1.5(argument)
  b <- function2.5(argument) 
  c <- function5(argument, argument2)
  grid.arrange(a, b, c, nrow = 1)
}
```


```{r}
function2.5 <- function(argument) 
{
  arransubsect %>%
  ggplot() +
  geom_sf() +
  theme_grey() +
  theme(axis.text.x=element_text(angle=45, hjust = 1)) +
  theme(legend.position="none") +
  geom_sf(data= argument, aes(fill = DataZone))
}
```

```{r}
function1.5 <- function(argument) 
{
  argument %>%
  ggplot() +
  geom_sf(aes(fill = Percentile)) +
  facet_wrap('year') +
  theme_grey() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  theme(legend.position="bottom")  
}
```

#2016
Now I apply the same functions to the post-2016 DataZones
#Plot the percentiles as bar charts.
Pre-2016
```{r}
arransimd2 <- dplyr::filter(arransimd, year < 2016)

arransimd2 %>%
ggplot(aes(x=year, y=Percentile)) +
  geom_bar(stat="identity") +
  facet_wrap('DataZone') +
  theme_grey() +
  labs(title = "Arran SIMD Datazones", x = "Year", y = "Percentile") +
  theme(plot.title = element_text(hjust = 0.5))
```

Post-2016
```{r}
arransimd3 <- dplyr::filter(arransimd, year >= 2016)

arransimd3 %>%
ggplot(aes(x=year, y=Percentile)) +
  geom_bar(stat="identity") +
  facet_wrap('DataZone') +
  theme_grey() +
  labs(title = "Arran SIMD Datazones", x = "Year", y = "Percentile") +
  theme(plot.title = element_text(hjust = 0.5))
```


#Pre-2016
```{r}
function7.5.1.2 <- function(argument)
{
  function7.5.1(pre2016list[[argument]],pre2016listID[[argument]])
}

lapply(1:7, function7.5.1.2)
```

#Post-2016
```{r}
function7.5.1.1 <- function(argument)
{
  function7.5.1(post2016list[[argument]],post2016listID[[argument]])
}

lapply(1:7, function7.5.1.1)
```

Now I create some plots.
```{r}
  ggplot() +
  geom_sf(data = arransubsect) +
  theme_grey() +
  geom_point(data = arrancoordinates, mapping = aes(x = longitude, y = latitude), size=1) +
  theme(axis.text.x=element_text(angle=45, hjust = 1)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  coord_sf(crs= 4326, datum = sf::st_crs(4326))
```
